# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4062cd39f700ad98e629c3b2d74bea7a8e3efc52ae25dbe830f22083054d7558c751e871da6862e3d80346a4d928436d94949ebca17d1684c86150e559e3fc6b

test:
  secret_key_base: 4ff9ea61287e566ec34da75cf9bdab26390882ec3f9c797448c5ce04b88ded5c987e99edfbc9987aba6d0556882f710332db17e543c35f01a0f952b4496610b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
